### ISSUE TITLE
What is "filesystem dispatch"?

### ISSUE THREAD

**Issue by techtonik** [AspenWeb/pando.py#557]
Sounds like rocket science..

**Comment by Changaco** [comment]
"dispatch" [means](https://en.wiktionary.org/wiki/dispatch) "To pass on for further processing, especially via a dispatch table", and in the case of a web framework the things being dispatched are HTTP requests.

In short, filesystem dispatch is like the old CGI/PHP/… mechanism: the code to generate a response for the `/hello/world` URL path is in the `$server_root/hello/world.{cgi,php,...}` file. Aspen uses the file extension is `spt` ([simplates](http://simplates.org/)), and the file paths can contain wildcards (e.g. `/%username/index.spt`).

Compared to others, filesystem dispatch means using a directory tree as the dispatch table, while Django uses [lists of regular expressions](https://docs.djangoproject.com/en/1.9/topics/http/urls/), and Flask uses patterns similar to Aspen's but [located in the code](http://flask.pocoo.org/docs/0.11/quickstart/#routing) instead of in the filesystem.
